### ISSUE TITLE
Constant messages in standard output

### ISSUE THREAD

**Issue by martonr** [AnimeniacYuuto/YuutoLib#1] opened 2015-12-15 10:36 UTC
A **inventory.InventoryHelper.mergeStack()** method has a _println()_ statement. (Line 132)

``` scala
System.out.println("Merging stack");
```

It does not cause any major problems but when running a server with several automated Auto Assemblers the console is filled with these messages, obscuring others.

**Comment by Flamarow** [comment] 2016-01-28 23:33
Although this seems slightly benign at first, it can actually be a huge problem on a server when this shows up. On my private server with just 2 people sharing a single base, I had this spam the console so much that the log file was half a GB after just half a day. Since I usually only restart it once per week, that means I have server logs that reach 6-8 GB which cannot be opened by most (if any) text editing programs. Surprisingly, Notepad++ has a 4 GB limit...

The text only shows up when handling recipes in the auto assembler that do not consume a non-stacking item. I have not tested for normal unstackable items such as pickaxes but I can confirm recipes that use Pam's pestle & mortar or Magic Crops various infusion stones cause the message to show up every time something crafts.

**Comment by AnimeniacYuuto** [comment] 2016-07-04 17:50
Fixed with 1.7.10-1.0.3

**Closed as completed by AnimeniacYuuto** 2016-07-04 17:50 UTC
